### ISSUE TITLE
Połączenie z InfluxDB

### ISSUE THREAD

**Issue by CapanoThomas** [bfaliszek/CCS811_InfluxDB#1]
informacyjnie, w szkicu u siebie, musiałem dodać w poniższym fragmencie kodu ",DB_USER, DB_PASSWORD" , inaczej sypało błędem połączenia z DB.

  

> if (influxdb.opendb(DATABASE**_,DB_USER, DB_PASSWORD_**) != DB_SUCCESS) {
  
> Serial.println("Connectingto database failed");

**Comment by bfaliszek** [comment]
Faktycznie, zapomniałem o sprawdzaniu loginu i hasła do bazy. Poprawiłem już kod w repo. Zaktualizowałem przy okazji bibliotekę do obsługi CCS811 😉
